apiVersion: apps/v1
kind: Deployment
metadata:
  name: portainer-deployment
  labels:
    app: portainer
spec:
  replicas: 1
  selector:
    matchLabels:
      app: portainer
  template:
    metadata:
      labels:
        app: portainer
    spec:
      containers:
      - name: portainer
        image: portainer/portainer:latest
        ports:
        - containerPort: 9000
        volumeMounts:
        - mountPath: /var/run/docker.sock
          name: docker-sock-volume
      volumes:
      - name: docker-sock-volume
        hostPath:
          path: /var/run/docker.sock
          type: File
      imagePullSecrets:
      - name: regcred
---
kind: Service
apiVersion: v1
metadata:
  name: portainer-service
  namespace: default
spec:
  selector:
    app: portainer
  type: NodePort
  ports:
    - port: 9000
      targetPort: 9000
      nodePort: 39000
  type: LoadBalancer