apiVersion: apps/v1
kind: Deployment
metadata:
  name: portainer-deployment
  labels:
    app: portainer
spec:
  replicas: 1
  selector:
    matchLabels:
      app: portainer
  template:
    metadata:
      labels:
        app: portainer
    spec:
      containers:
      - name: portainer
        image: portainer/portainer:latest
        ports:
        - containerPort: 9000
      imagePullSecrets:
      - name: regcred