---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: logs-volume
  labels:
    type: local
spec:
  capacity:
    storage: 10Gi
  accessModes:
  - ReadWriteOnce
  hostPath:
    path: "/tmp/proxyserver"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: logs-volume-claim
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: proxyserver-deployment
  labels:
    app: proxyserver
    name: proxyserver-proxy-deploy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: proxyserver_nginx
  template:
    metadata:
      labels:
        app: proxyserver_nginx
        name: proxyserver-proxy
    spec:
      containers:
      - name: proxyserver
        image: uzzal2k5/proxyserver:latest
        ports:
        - name: http-port
          containerPort: 80
        - name: https-port
          containerPort: 443
        volumeMounts:
        - mountPath: /var/log/nginx
          name: nginx-log-volume
      restartPolicy: Always
      hostNetwork: true
      dnsPolicy: ClusterFirstWithHostNet
      volumes:
      - name: nginx-log-volume
        persistentVolumeClaim:
          claimName: logs-volume-claim
      imagePullSecrets:
      - name: regcred
---
apiVersion: v1
kind: Service
metadata:
  name: proxyserver-service
  namespace: default
spec:
  selector:
    app: proxyserver_nginx
    name: proxyserver-proxy
  ports:
  - name: server-https-port
    port: 443
    targetPort: 443
  type: LoadBalancer
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: proxyserver-ingress
spec:
  backend:
    serviceName: proxyserver-service
    servicePort: 443